// SDL2Sharp
//
// Copyright (C) 2021-2024 Ronald van Manen <rvanmanen@gmail.com>
//
// This software is provided 'as-is', without any express or implied
// warranty.  In no event will the authors be held liable for any damages
// arising from the use of this software.
// 
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it
// freely, subject to the following restrictions:
//
// 1. The origin of this software must not be misrepresented; you must not
//    claim that you wrote the original software. If you use this software
//    in a product, an acknowledgment in the product documentation would be
//    appreciated but is not required.
// 2. Altered source versions must be plainly marked as such, and must not be
//    misrepresented as being the original software.
// 3. This notice may not be removed or altered from any source distribution.

using SDL2Sharp.Interop;

namespace SDL2Sharp
{
    public enum KeyCode
    {
        Unknown = SDL_KeyCode.SDLK_UNKNOWN,
        Return = SDL_KeyCode.SDLK_RETURN,
        Escape = SDL_KeyCode.SDLK_ESCAPE,
        Backspace = SDL_KeyCode.SDLK_BACKSPACE,
        Tab = SDL_KeyCode.SDLK_TAB,
        Space = SDL_KeyCode.SDLK_SPACE,
        Exclamation = SDL_KeyCode.SDLK_EXCLAIM,
        DoubleQuote = SDL_KeyCode.SDLK_QUOTEDBL,
        Hash = SDL_KeyCode.SDLK_HASH,
        Percent = SDL_KeyCode.SDLK_PERCENT,
        Dollar = SDL_KeyCode.SDLK_DOLLAR,
        Ampersand = SDL_KeyCode.SDLK_AMPERSAND,
        Quote = SDL_KeyCode.SDLK_QUOTE,
        LeftParenthesis = SDL_KeyCode.SDLK_LEFTPAREN,
        RightParenthesis = SDL_KeyCode.SDLK_RIGHTPAREN,
        Asterisk = SDL_KeyCode.SDLK_ASTERISK,
        Plus = SDL_KeyCode.SDLK_PLUS,
        Comma = SDL_KeyCode.SDLK_COMMA,
        Minus = SDL_KeyCode.SDLK_MINUS,
        Period = SDL_KeyCode.SDLK_PERIOD,
        Slash = SDL_KeyCode.SDLK_SLASH,
        D0 = SDL_KeyCode.SDLK_0,
        D1 = SDL_KeyCode.SDLK_1,
        D2 = SDL_KeyCode.SDLK_2,
        D3 = SDL_KeyCode.SDLK_3,
        D4 = SDL_KeyCode.SDLK_4,
        D5 = SDL_KeyCode.SDLK_5,
        D6 = SDL_KeyCode.SDLK_6,
        D7 = SDL_KeyCode.SDLK_7,
        D8 = SDL_KeyCode.SDLK_8,
        D9 = SDL_KeyCode.SDLK_9,
        Colon = SDL_KeyCode.SDLK_COLON,
        Semicolon = SDL_KeyCode.SDLK_SEMICOLON,
        Less = SDL_KeyCode.SDLK_LESS,
        Equals = SDL_KeyCode.SDLK_EQUALS,
        Greater = SDL_KeyCode.SDLK_GREATER,
        Question = SDL_KeyCode.SDLK_QUESTION,
        At = SDL_KeyCode.SDLK_AT,
        LeftBracket = SDL_KeyCode.SDLK_LEFTBRACKET,
        Backslash = SDL_KeyCode.SDLK_BACKSLASH,
        RightBracket = SDL_KeyCode.SDLK_RIGHTBRACKET,
        Caret = SDL_KeyCode.SDLK_CARET,
        Underscore = SDL_KeyCode.SDLK_UNDERSCORE,
        Backqoute = SDL_KeyCode.SDLK_BACKQUOTE,
        A = SDL_KeyCode.SDLK_a,
        B = SDL_KeyCode.SDLK_b,
        C = SDL_KeyCode.SDLK_c,
        D = SDL_KeyCode.SDLK_d,
        E = SDL_KeyCode.SDLK_e,
        F = SDL_KeyCode.SDLK_f,
        G = SDL_KeyCode.SDLK_g,
        H = SDL_KeyCode.SDLK_h,
        I = SDL_KeyCode.SDLK_i,
        J = SDL_KeyCode.SDLK_j,
        K = SDL_KeyCode.SDLK_k,
        L = SDL_KeyCode.SDLK_l,
        M = SDL_KeyCode.SDLK_m,
        N = SDL_KeyCode.SDLK_n,
        O = SDL_KeyCode.SDLK_o,
        P = SDL_KeyCode.SDLK_p,
        Q = SDL_KeyCode.SDLK_q,
        R = SDL_KeyCode.SDLK_r,
        S = SDL_KeyCode.SDLK_s,
        T = SDL_KeyCode.SDLK_t,
        U = SDL_KeyCode.SDLK_u,
        V = SDL_KeyCode.SDLK_v,
        W = SDL_KeyCode.SDLK_w,
        X = SDL_KeyCode.SDLK_x,
        Y = SDL_KeyCode.SDLK_y,
        Z = SDL_KeyCode.SDLK_z,
        CapsLock = SDL_KeyCode.SDLK_CAPSLOCK,
        F1 = SDL_KeyCode.SDLK_F1,
        F2 = SDL_KeyCode.SDLK_F2,
        F3 = SDL_KeyCode.SDLK_F3,
        F4 = SDL_KeyCode.SDLK_F4,
        F5 = SDL_KeyCode.SDLK_F5,
        F6 = SDL_KeyCode.SDLK_F6,
        F7 = SDL_KeyCode.SDLK_F7,
        F8 = SDL_KeyCode.SDLK_F8,
        F9 = SDL_KeyCode.SDLK_F9,
        F10 = SDL_KeyCode.SDLK_F10,
        F11 = SDL_KeyCode.SDLK_F11,
        F12 = SDL_KeyCode.SDLK_F12,
        PrintScreen = SDL_KeyCode.SDLK_PRINTSCREEN,
        ScrollLock = SDL_KeyCode.SDLK_SCROLLLOCK,
        Pause = SDL_KeyCode.SDLK_PAUSE,
        Insert = SDL_KeyCode.SDLK_INSERT,
        Home = SDL_KeyCode.SDLK_HOME,
        PageUp = SDL_KeyCode.SDLK_PAGEUP,
        Delete = SDL_KeyCode.SDLK_DELETE,
        End = SDL_KeyCode.SDLK_END,
        PageDown = SDL_KeyCode.SDLK_PAGEDOWN,
        Right = SDL_KeyCode.SDLK_RIGHT,
        Left = SDL_KeyCode.SDLK_LEFT,
        Down = SDL_KeyCode.SDLK_DOWN,
        Up = SDL_KeyCode.SDLK_UP,
        NumLockClear = SDL_KeyCode.SDLK_NUMLOCKCLEAR,
        KeypadDivide = SDL_KeyCode.SDLK_KP_DIVIDE,
        KeypadMultiply = SDL_KeyCode.SDLK_KP_MULTIPLY,
        KeypadMinus = SDL_KeyCode.SDLK_KP_MINUS,
        KeypadPlus = SDL_KeyCode.SDLK_KP_PLUS,
        KeypadEnter = SDL_KeyCode.SDLK_KP_ENTER,
        Keypad1 = SDL_KeyCode.SDLK_KP_1,
        Keypad2 = SDL_KeyCode.SDLK_KP_2,
        Keypad3 = SDL_KeyCode.SDLK_KP_3,
        Keypad4 = SDL_KeyCode.SDLK_KP_4,
        Keypad5 = SDL_KeyCode.SDLK_KP_5,
        Keypad6 = SDL_KeyCode.SDLK_KP_6,
        Keypad7 = SDL_KeyCode.SDLK_KP_7,
        Keypad8 = SDL_KeyCode.SDLK_KP_8,
        Keypad9 = SDL_KeyCode.SDLK_KP_9,
        Keypad0 = SDL_KeyCode.SDLK_KP_0,
        KeypadPeriod = SDL_KeyCode.SDLK_KP_PERIOD,
        Application = SDL_KeyCode.SDLK_APPLICATION,
        Power = SDL_KeyCode.SDLK_POWER,
        KeypadEquals = SDL_KeyCode.SDLK_KP_EQUALS,
        F13 = SDL_KeyCode.SDLK_F13,
        F14 = SDL_KeyCode.SDLK_F14,
        F15 = SDL_KeyCode.SDLK_F15,
        F16 = SDL_KeyCode.SDLK_F16,
        F17 = SDL_KeyCode.SDLK_F17,
        F18 = SDL_KeyCode.SDLK_F18,
        F19 = SDL_KeyCode.SDLK_F19,
        F20 = SDL_KeyCode.SDLK_F20,
        F21 = SDL_KeyCode.SDLK_F21,
        F22 = SDL_KeyCode.SDLK_F22,
        F23 = SDL_KeyCode.SDLK_F23,
        F24 = SDL_KeyCode.SDLK_F24,
        Execute = SDL_KeyCode.SDLK_EXECUTE,
        Help = SDL_KeyCode.SDLK_HELP,
        Menu = SDL_KeyCode.SDLK_MENU,
        Select = SDL_KeyCode.SDLK_SELECT,
        Stop = SDL_KeyCode.SDLK_STOP,
        Again = SDL_KeyCode.SDLK_AGAIN,
        Undo = SDL_KeyCode.SDLK_UNDO,
        Cut = SDL_KeyCode.SDLK_CUT,
        Copy = SDL_KeyCode.SDLK_COPY,
        Paste = SDL_KeyCode.SDLK_PASTE,
        Find = SDL_KeyCode.SDLK_FIND,
        Mute = SDL_KeyCode.SDLK_MUTE,
        VolumeUp = SDL_KeyCode.SDLK_VOLUMEUP,
        VolumeDown = SDL_KeyCode.SDLK_VOLUMEDOWN,
        KeypadComma = SDL_KeyCode.SDLK_KP_COMMA,
        KeypadEqualsAS400 = SDL_KeyCode.SDLK_KP_EQUALSAS400,
        AltErase = SDL_KeyCode.SDLK_ALTERASE,
        SysReq = SDL_KeyCode.SDLK_SYSREQ,
        Cancel = SDL_KeyCode.SDLK_CANCEL,
        Clear = SDL_KeyCode.SDLK_CLEAR,
        Prior = SDL_KeyCode.SDLK_PRIOR,
        Return2 = SDL_KeyCode.SDLK_RETURN2,
        Separator = SDL_KeyCode.SDLK_SEPARATOR,
        Out = SDL_KeyCode.SDLK_OUT,
        Oper = SDL_KeyCode.SDLK_OPER,
        ClearAgain = SDL_KeyCode.SDLK_CLEARAGAIN,
        CrSel = SDL_KeyCode.SDLK_CRSEL,
        ExSel = SDL_KeyCode.SDLK_EXSEL,
        Keypad00 = SDL_KeyCode.SDLK_KP_00,
        Keypad000 = SDL_KeyCode.SDLK_KP_000,
        ThoudsandSeparator = SDL_KeyCode.SDLK_THOUSANDSSEPARATOR,
        DecimalSeparator = SDL_KeyCode.SDLK_DECIMALSEPARATOR,
        CurrencyUnit = SDL_KeyCode.SDLK_CURRENCYUNIT,
        CurrencySubunit = SDL_KeyCode.SDLK_CURRENCYSUBUNIT,
        KeypadLeftParenthesis = SDL_KeyCode.SDLK_KP_LEFTPAREN,
        KeypadRightParenthesis = SDL_KeyCode.SDLK_KP_RIGHTPAREN,
        KeypadLeftBrace = SDL_KeyCode.SDLK_KP_LEFTBRACE,
        KeypadRightBrace = SDL_KeyCode.SDLK_KP_RIGHTBRACE,
        KeypadTAB = SDL_KeyCode.SDLK_KP_TAB,
        KeypadBACKSPACE = SDL_KeyCode.SDLK_KP_BACKSPACE,
        KeypadA = SDL_KeyCode.SDLK_KP_A,
        KeypadB = SDL_KeyCode.SDLK_KP_B,
        KeypadC = SDL_KeyCode.SDLK_KP_C,
        KeypadD = SDL_KeyCode.SDLK_KP_D,
        KeypadE = SDL_KeyCode.SDLK_KP_E,
        KeypadF = SDL_KeyCode.SDLK_KP_F,
        KeypadXor = SDL_KeyCode.SDLK_KP_XOR,
        KeypadPower = SDL_KeyCode.SDLK_KP_POWER,
        KeypadPercent = SDL_KeyCode.SDLK_KP_PERCENT,
        KeypadLess = SDL_KeyCode.SDLK_KP_LESS,
        KeypadGreater = SDL_KeyCode.SDLK_KP_GREATER,
        KeypadAmpersand = SDL_KeyCode.SDLK_KP_AMPERSAND,
        KeypadDoubleAmpersand = SDL_KeyCode.SDLK_KP_DBLAMPERSAND,
        KeypadVerticalBar = SDL_KeyCode.SDLK_KP_VERTICALBAR,
        KeypadDoubleVerticalBar = SDL_KeyCode.SDLK_KP_DBLVERTICALBAR,
        KeypadColon = SDL_KeyCode.SDLK_KP_COLON,
        KeypadHash = SDL_KeyCode.SDLK_KP_HASH,
        KeypadSpace = SDL_KeyCode.SDLK_KP_SPACE,
        KeypadAt = SDL_KeyCode.SDLK_KP_AT,
        KeypadExcalmation = SDL_KeyCode.SDLK_KP_EXCLAM,
        KeypadMemStore = SDL_KeyCode.SDLK_KP_MEMSTORE,
        KeypadMemRecall = SDL_KeyCode.SDLK_KP_MEMRECALL,
        KeypadMemClear = SDL_KeyCode.SDLK_KP_MEMCLEAR,
        KeypadMemAdd = SDL_KeyCode.SDLK_KP_MEMADD,
        KeypadMemSubtract = SDL_KeyCode.SDLK_KP_MEMSUBTRACT,
        KeypadMemMultiply = SDL_KeyCode.SDLK_KP_MEMMULTIPLY,
        KeypadMemDivide = SDL_KeyCode.SDLK_KP_MEMDIVIDE,
        KeypadPlusMinus = SDL_KeyCode.SDLK_KP_PLUSMINUS,
        KeypadClear = SDL_KeyCode.SDLK_KP_CLEAR,
        KeypadClearEntry = SDL_KeyCode.SDLK_KP_CLEARENTRY,
        KeypadBinary = SDL_KeyCode.SDLK_KP_BINARY,
        KeypadOctal = SDL_KeyCode.SDLK_KP_OCTAL,
        KeypadDecimal = SDL_KeyCode.SDLK_KP_DECIMAL,
        KeypadHexadecimal = SDL_KeyCode.SDLK_KP_HEXADECIMAL,
        LeftCtrl = SDL_KeyCode.SDLK_LCTRL,
        LeftShift = SDL_KeyCode.SDLK_LSHIFT,
        LeftAlt = SDL_KeyCode.SDLK_LALT,
        LeftGui = SDL_KeyCode.SDLK_LGUI,
        RightCtrl = SDL_KeyCode.SDLK_RCTRL,
        RightShift = SDL_KeyCode.SDLK_RSHIFT,
        RightAlt = SDL_KeyCode.SDLK_RALT,
        RightGui = SDL_KeyCode.SDLK_RGUI,
        Mode = SDL_KeyCode.SDLK_MODE,
        AudioNext = SDL_KeyCode.SDLK_AUDIONEXT,
        AudioPrev = SDL_KeyCode.SDLK_AUDIOPREV,
        AudioStop = SDL_KeyCode.SDLK_AUDIOSTOP,
        AudioPlay = SDL_KeyCode.SDLK_AUDIOPLAY,
        AudioMute = SDL_KeyCode.SDLK_AUDIOMUTE,
        MediaSelect = SDL_KeyCode.SDLK_MEDIASELECT,
        Www = SDL_KeyCode.SDLK_WWW,
        Mail = SDL_KeyCode.SDLK_MAIL,
        Calculator = SDL_KeyCode.SDLK_CALCULATOR,
        Computer = SDL_KeyCode.SDLK_COMPUTER,
        AcSearch = SDL_KeyCode.SDLK_AC_SEARCH,
        AcHome = SDL_KeyCode.SDLK_AC_HOME,
        AcBack = SDL_KeyCode.SDLK_AC_BACK,
        AcForward = SDL_KeyCode.SDLK_AC_FORWARD,
        AcStop = SDL_KeyCode.SDLK_AC_STOP,
        AcRefresh = SDL_KeyCode.SDLK_AC_REFRESH,
        AcBookmarks = SDL_KeyCode.SDLK_AC_BOOKMARKS,
        BrightnessDown = SDL_KeyCode.SDLK_BRIGHTNESSDOWN,
        BrightnessUp = SDL_KeyCode.SDLK_BRIGHTNESSUP,
        DisplaySwitch = SDL_KeyCode.SDLK_DISPLAYSWITCH,
        KeyboardIlluminationToggle = SDL_KeyCode.SDLK_KBDILLUMTOGGLE,
        KeyboardIlluminationDown = SDL_KeyCode.SDLK_KBDILLUMDOWN,
        KeyboardIlluminationUp = SDL_KeyCode.SDLK_KBDILLUMUP,
        Eject = SDL_KeyCode.SDLK_EJECT,
        Sleep = SDL_KeyCode.SDLK_SLEEP,
        App1 = SDL_KeyCode.SDLK_APP1,
        App2 = SDL_KeyCode.SDLK_APP2,
        AudioRewind = SDL_KeyCode.SDLK_AUDIOREWIND,
        AudioFastforward = SDL_KeyCode.SDLK_AUDIOFASTFORWARD,
    }
}
