name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-dependencies:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - run: |
        nuget pack ".\packages\sdl2\SDL2.nuspec" -OutputDirectory ".\packages\"
        nuget pack ".\packages\sdl2.runtime.win-x86/SDL2.runtime.win-x86.nuspec" -OutputDirectory ".\packages\"
        nuget pack ".\packages\sdl2.runtime.win-x64/SDL2.runtime.win-x64.nuspec" -OutputDirectory ".\packages\"
    - run: dotnet nuget push ".\packages\*.nupkg" --source https://nuget.pkg.github.com/ronaldvanmanen/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
  windows-x64:
    runs-on: ${{ matrix.os }}-latest
    needs: [ build-dependencies ]
    strategy:
      matrix:
        architecture: [ x64 ]
        configuration: [ debug, release ]
        os: [ windows ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: ./scripts/cibuild.cmd -configuration ${{ matrix.configuration }} -architecture ${{ matrix.architecture }}
      shell: cmd
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}_${{ matrix.configuration }}_${{ matrix.architecture }}
        path: |
          ./artifacts/bin/**/*
          ./artifacts/log/**/*
          ./artifacts/pkg/**/*
          ./artifacts/tst/**/*
        if-no-files-found: error
  windows-x86:
    runs-on: ${{ matrix.os }}-latest
    needs: [ build-dependencies ]
    strategy:
      matrix:
        architecture: [ x86 ]
        configuration: [ debug, release ]
        os: [ windows ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: ./scripts/cibuild.cmd -configuration ${{ matrix.configuration }} -architecture ${{ matrix.architecture }} /p:PlatformTarget=${{ matrix.architecture }}
      shell: cmd
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}_${{ matrix.configuration }}_x86
        path: |
          ./artifacts/bin/**/*
          ./artifacts/log/**/*
          ./artifacts/pkg/**/*
          ./artifacts/tst/**/*
        if-no-files-found: error
  build-nuget:
    runs-on: windows-latest
    needs: [ build-dependencies ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: ./scripts/cibuild.cmd -configuration release -architecture x64
      shell: cmd
      env:
        EXCLUDE_RUN_ID_FROM_PACKAGE: true
    - uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: |
          ./artifacts/bin/**/*
          ./artifacts/log/**/*
          ./artifacts/pkg/**/*
          ./artifacts/tst/**/*
        if-no-files-found: error
  publish-nightlies-github:
    runs-on: windows-latest
    if: ${{ github.event_name == 'push' }}
    needs: [ windows-x64, windows-x86, build-nuget ]
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: windows_release_x64
        path: ./artifacts
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet nuget push "./artifacts/pkg/Release/*.nupkg" --source https://nuget.pkg.github.com/ronaldvanmanen/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
